#ifndef InstructionTable_hpp
#define InstructionTable_hpp

#include <array>
#include <functional>

#include "Add.hpp"
#include "And.hpp"
#include "Bit.hpp"
#include "Compare.hpp"
#include "Dec.hpp"
#include "Exchange.hpp"
#include "Inc.hpp"
#include "Jump.hpp"
#include "Load.hpp"
#include "Misc.hpp"
#include "Or.hpp"
#include "Pop.hpp"
#include "Push.hpp"
#include "Reset.hpp"
#include "Rotate.hpp"
#include "Set.hpp"
#include "Shift.hpp"
#include "Sub.hpp"
#include "Xor.hpp"


//Function tables
void bit_instructions();
void ix_instructions();
void ix_bit_instructions();
void misc_instructions();
void iy_instructions();
void iy_bit_instructions();

// std::vector<INSTRUCTION> main_instruction_table;
// std::vector<INSTRUCTION> bit_instruction_table;			// opcode: CB
// std::vector<INSTRUCTION> ix_instruction_table;			// opcode: DD
// std::vector<INSTRUCTION> ix_bit_instruction_table;		// opcode: DD CB
// std::vector<INSTRUCTION> misc_instruction_table;		    // opcode: ED
// std::vector<INSTRUCTION> iy_instruction_table;			// opcode: FD
// std::vector<INSTRUCTION> iy_bit_instruction_table;		// opcode: FD CB

//Instruction tables
struct INSTRUCTION {
    const char* opcode;
    std::function<void()> func_ptr;

    INSTRUCTION(const char* name, std::function<void()> fp) : opcode(name), func_ptr(fp){}
};

constexpr std::array main_instruction_table = {
    INSTRUCTION("00", NOP_implied ),                   INSTRUCTION("01", LD_register_immediate_extended_16_bit ), INSTRUCTION("02", LD_register_indirect_register_BC ), INSTRUCTION("03", INC_implied_register_extended ),   INSTRUCTION("04", INC_implied_register ),          INSTRUCTION("05", DEC_implied_register ),            INSTRUCTION("06", LD_register_immediate ),          INSTRUCTION("07", RLCA_implied ),                  INSTRUCTION("08", EX_implied_implied_af ), INSTRUCTION("09", ADD_implied_register_extended ), INSTRUCTION("0A", LD_register_register_indirect_BC ), INSTRUCTION("0B", DEC_implied_register_extended ), INSTRUCTION("0C", INC_implied_register ), INSTRUCTION("0D", DEC_implied_register ), INSTRUCTION("0E", LD_register_immediate ),         INSTRUCTION("0F", RRCA_implied ),
    INSTRUCTION("10", DJNZ_immediate ),                INSTRUCTION("11", LD_register_immediate_extended_16_bit ), INSTRUCTION("12", LD_register_indirect_register_DE ), INSTRUCTION("13", INC_implied_register_extended ),   INSTRUCTION("14", INC_implied_register ),          INSTRUCTION("15", DEC_implied_register ),            INSTRUCTION("16", LD_register_immediate ),          INSTRUCTION("17", RLA_implied ),                   INSTRUCTION("18", JR_relative ),           INSTRUCTION("19", ADD_implied_register_extended ), INSTRUCTION("1A", LD_register_register_indirect_DE ), INSTRUCTION("1B", DEC_implied_register_extended ), INSTRUCTION("1C", INC_implied_register ), INSTRUCTION("1D", DEC_implied_register ), INSTRUCTION("1E", LD_register_immediate ),         INSTRUCTION("1F", RRA_implied ),
    INSTRUCTION("20", JR_cc_relative ),                INSTRUCTION("21", LD_register_immediate_extended_16_bit ), INSTRUCTION("22", LD_extended_register_hl ),          INSTRUCTION("23", INC_implied_register_extended ),   INSTRUCTION("24", INC_implied_register ),          INSTRUCTION("25", DEC_implied_register ),            INSTRUCTION("26", LD_register_immediate ),          INSTRUCTION("27", DAA_implied ),                   INSTRUCTION("28", JR_cc_relative ),        INSTRUCTION("29", ADD_implied_register_extended ), INSTRUCTION("2A", LD_register_extended_hl ),          INSTRUCTION("2B", DEC_implied_register_extended ), INSTRUCTION("2C", INC_implied_register ), INSTRUCTION("2D", DEC_implied_register ), INSTRUCTION("2E", LD_register_immediate ),         INSTRUCTION("2F", CPL_implied ),
    INSTRUCTION("30", JR_cc_relative ),                INSTRUCTION("31", LD_register_immediate_extended_16_bit ), INSTRUCTION("32", LD_extended_register ),             INSTRUCTION("33", INC_implied_register_extended ),   INSTRUCTION("34", INC_implied_register_indirect ), INSTRUCTION("35", DEC_implied_register_indirect ),   INSTRUCTION("36", LD_register_indirect_immediate ), INSTRUCTION("37", SCF_implied ),                   INSTRUCTION("38", JR_cc_relative ),        INSTRUCTION("39", ADD_implied_register_extended ), INSTRUCTION("3A", LD_register_extended ),             INSTRUCTION("3B", DEC_implied_register_extended ), INSTRUCTION("3C", INC_implied_register ), INSTRUCTION("3D", DEC_implied_register ), INSTRUCTION("3E", LD_register_immediate ),         INSTRUCTION("3F", CCF_implied ),
    INSTRUCTION("40", LD_register_register ),          INSTRUCTION("41", LD_register_register ),                  INSTRUCTION("42", LD_register_register ),             INSTRUCTION("43", LD_register_register ),            INSTRUCTION("44", LD_register_register ),          INSTRUCTION("45", LD_register_register ),            INSTRUCTION("46", LD_register_register_indirect ),  INSTRUCTION("47", LD_register_register ),          INSTRUCTION("48", LD_register_register ),  INSTRUCTION("49", LD_register_register ),          INSTRUCTION("4A", LD_register_register ),             INSTRUCTION("4B", LD_register_register ),          INSTRUCTION("4C", LD_register_register ), INSTRUCTION("4D", LD_register_register ), INSTRUCTION("4E", LD_register_register_indirect ), INSTRUCTION("4F", LD_register_register ),
    INSTRUCTION("50", LD_register_register ),          INSTRUCTION("51", LD_register_register ),                  INSTRUCTION("52", LD_register_register ),             INSTRUCTION("53", LD_register_register ),            INSTRUCTION("54", LD_register_register ),          INSTRUCTION("55", LD_register_register ),            INSTRUCTION("56", LD_register_register_indirect ),  INSTRUCTION("57", LD_register_register ),          INSTRUCTION("58", LD_register_register ),  INSTRUCTION("59", LD_register_register ),          INSTRUCTION("5A", LD_register_register ),             INSTRUCTION("5B", LD_register_register ),          INSTRUCTION("5C", LD_register_register ), INSTRUCTION("5D", LD_register_register ), INSTRUCTION("5E", LD_register_register_indirect ), INSTRUCTION("5F", LD_register_register ),
    INSTRUCTION("60", LD_register_register ),          INSTRUCTION("61", LD_register_register ),                  INSTRUCTION("62", LD_register_register ),             INSTRUCTION("63", LD_register_register ),            INSTRUCTION("64", LD_register_register ),          INSTRUCTION("65", LD_register_register ),            INSTRUCTION("66", LD_register_register_indirect ),  INSTRUCTION("67", LD_register_register ),          INSTRUCTION("68", LD_register_register ),  INSTRUCTION("69", LD_register_register ),          INSTRUCTION("6A", LD_register_register ),             INSTRUCTION("6B", LD_register_register ),          INSTRUCTION("6C", LD_register_register ), INSTRUCTION("6D", LD_register_register ), INSTRUCTION("6E", LD_register_register_indirect ), INSTRUCTION("6F", LD_register_register ),
    INSTRUCTION("70", LD_register_indirect_register ), INSTRUCTION("71", LD_register_indirect_register ),         INSTRUCTION("72", LD_register_indirect_register ),    INSTRUCTION("73", LD_register_indirect_register ),   INSTRUCTION("74", LD_register_indirect_register ), INSTRUCTION("75", LD_register_indirect_register ),   INSTRUCTION("76", nullptr ),                     INSTRUCTION("77", LD_register_indirect_register ), INSTRUCTION("78", LD_register_register ),  INSTRUCTION("79", LD_register_register ),          INSTRUCTION("7A", LD_register_register ),             INSTRUCTION("7B", LD_register_register ),          INSTRUCTION("7C", LD_register_register ), INSTRUCTION("7D", LD_register_register ), INSTRUCTION("7E", LD_register_register_indirect ), INSTRUCTION("7F", LD_register_register ),
    INSTRUCTION("80", ADD_implied_register ),          INSTRUCTION("81", ADD_implied_register ),                  INSTRUCTION("82", ADD_implied_register ),             INSTRUCTION("83", ADD_implied_register ),            INSTRUCTION("84", ADD_implied_register ),          INSTRUCTION("85", ADD_implied_register ),            INSTRUCTION("86", ADD_implied_register_indirect ),  INSTRUCTION("87", ADD_implied_register ),          INSTRUCTION("88", ADC_implied_register ),  INSTRUCTION("89", ADC_implied_register ),          INSTRUCTION("8A", ADC_implied_register ),             INSTRUCTION("8B", ADC_implied_register ),          INSTRUCTION("8C", ADC_implied_register ), INSTRUCTION("8D", ADC_implied_register ), INSTRUCTION("8E", ADC_implied_register_indirect ), INSTRUCTION("8F", ADC_implied_register ),
    INSTRUCTION("90", SUB_implied_register ),          INSTRUCTION("91", SUB_implied_register ),                  INSTRUCTION("92", SUB_implied_register ),             INSTRUCTION("93", SUB_implied_register ),            INSTRUCTION("94", SUB_implied_register ),          INSTRUCTION("95", SUB_implied_register ),            INSTRUCTION("96", SUB_implied_register_indirect ),  INSTRUCTION("97", SUB_implied_register ),          INSTRUCTION("98", SBC_implied_register ),  INSTRUCTION("99", SBC_implied_register ),          INSTRUCTION("9A", SBC_implied_register ),             INSTRUCTION("9B", SBC_implied_register ),          INSTRUCTION("9C", SBC_implied_register ), INSTRUCTION("9D", SBC_implied_register ), INSTRUCTION("9E", SBC_implied_register_indirect ), INSTRUCTION("9F", SBC_implied_register ),
    INSTRUCTION("A0", AND_implied_register ),          INSTRUCTION("A1", AND_implied_register ),                  INSTRUCTION("A2", AND_implied_register ),             INSTRUCTION("A3", AND_implied_register ),            INSTRUCTION("A4", AND_implied_register ),          INSTRUCTION("A5", AND_implied_register ),            INSTRUCTION("A6", AND_implied_register_indirect ),  INSTRUCTION("A7", AND_implied_register ),          INSTRUCTION("A8", XOR_implied_register ),  INSTRUCTION("A9", XOR_implied_register ),          INSTRUCTION("AA", XOR_implied_register ),             INSTRUCTION("AB", XOR_implied_register ),          INSTRUCTION("AC", XOR_implied_register ), INSTRUCTION("AD", XOR_implied_register ), INSTRUCTION("AE", XOR_implied_register_indirect ), INSTRUCTION("AF", XOR_implied_register ),
    INSTRUCTION("B0", OR_implied_register ),           INSTRUCTION("B1", OR_implied_register ),                   INSTRUCTION("B2", OR_implied_register ),              INSTRUCTION("B3", OR_implied_register ),             INSTRUCTION("B4", OR_implied_register ),           INSTRUCTION("B5", OR_implied_register ),             INSTRUCTION("B6", OR_implied_register_indirect ),   INSTRUCTION("B7", OR_implied_register ),           INSTRUCTION("B8", CP_implied_register ),   INSTRUCTION("B9", CP_implied_register ),           INSTRUCTION("BA", CP_implied_register ),              INSTRUCTION("BB", CP_implied_register ),           INSTRUCTION("BC", CP_implied_register ),  INSTRUCTION("BD", CP_implied_register ),  INSTRUCTION("BE", CP_implied_register_indirect ),  INSTRUCTION("BF", CP_implied_register ),
    INSTRUCTION("C0", nullptr ),                     INSTRUCTION("C1", POP_register_indirect_register ),        INSTRUCTION("C2", JP_cc_immediate ),                  INSTRUCTION("C3", JP_immediate ),                    INSTRUCTION("C4", nullptr ),                    INSTRUCTION("C5", PUSH_register_indirect_register ), INSTRUCTION("C6", ADD_implied_immediate ),          INSTRUCTION("C7", nullptr ),                     INSTRUCTION("C8", nullptr ),            INSTRUCTION("C9", nullptr ),                     INSTRUCTION("CA", JP_cc_immediate ),                  INSTRUCTION("CB", bit_instructions ),              INSTRUCTION("CC", nullptr ),            INSTRUCTION("CD", nullptr ),           INSTRUCTION("CE", ADC_implied_immediate ),         INSTRUCTION("CF", nullptr ),
    INSTRUCTION("D0", nullptr ),                     INSTRUCTION("D1", POP_register_indirect_register ),        INSTRUCTION("D2", JP_cc_immediate ),                  INSTRUCTION("D3", nullptr ),                      INSTRUCTION("D4", nullptr ),                     INSTRUCTION("D5", PUSH_register_indirect_register ), INSTRUCTION("D6", SUB_implied_immediate ),          INSTRUCTION("D7", nullptr ),                     INSTRUCTION("D8", nullptr ),            INSTRUCTION("D9", EXX_implied_implied ),           INSTRUCTION("DA", JP_cc_immediate ),                  INSTRUCTION("DB", nullptr ),                     INSTRUCTION("DC", nullptr ),            INSTRUCTION("DD", ix_instructions ),      INSTRUCTION("DE", SBC_implied_immediate ),         INSTRUCTION("DF", nullptr ),
    INSTRUCTION("E0", nullptr ),                     INSTRUCTION("E1", POP_register_indirect_register ),        INSTRUCTION("E2", JP_cc_immediate ),                  INSTRUCTION("E3", EX_register_indirect_implied_hl ), INSTRUCTION("E4", nullptr ),                     INSTRUCTION("E5", PUSH_register_indirect_register ), INSTRUCTION("E6", AND_implied_immediate ),          INSTRUCTION("E7", nullptr ),                     INSTRUCTION("E8", nullptr ),            INSTRUCTION("E9", JP_implict ),                    INSTRUCTION("EA", JP_cc_immediate ),                  INSTRUCTION("EB", EX_implied_implied ),            INSTRUCTION("EC", nullptr ),            INSTRUCTION("ED", misc_instructions ),    INSTRUCTION("EE", XOR_implied_immediate ),         INSTRUCTION("EF", nullptr ),
    INSTRUCTION("F0", nullptr ),                     INSTRUCTION("F1", POP_register_indirect_register ),        INSTRUCTION("F2", JP_cc_immediate ),                  INSTRUCTION("F3", nullptr ),                       INSTRUCTION("F4", nullptr ),                    INSTRUCTION("F5", PUSH_register_indirect_register ), INSTRUCTION("F6", OR_implied_immediate ),           INSTRUCTION("F7", nullptr ),                     INSTRUCTION("F8", nullptr ),             INSTRUCTION("F9", LD_register_register_hl ),       INSTRUCTION("FA", JP_cc_immediate ),                  INSTRUCTION("FB", nullptr ),                    INSTRUCTION("FC", nullptr ),            INSTRUCTION("FD", iy_instructions ),      INSTRUCTION("FE", CP_implied_immediate ),          INSTRUCTION("FF", nullptr )
};

constexpr std::array misc_instruction_table = {
    INSTRUCTION("00", nullptr), INSTRUCTION("01", nullptr), INSTRUCTION("02", nullptr), INSTRUCTION("03", nullptr), INSTRUCTION("04", nullptr), INSTRUCTION("05", nullptr), INSTRUCTION("06", nullptr), INSTRUCTION("07", nullptr), INSTRUCTION("08", nullptr), INSTRUCTION("09", nullptr), INSTRUCTION("0A", nullptr), INSTRUCTION("0B", nullptr), INSTRUCTION("0C", nullptr), INSTRUCTION("0D", nullptr), INSTRUCTION("0E", nullptr), INSTRUCTION("0F", nullptr),
    INSTRUCTION("10", nullptr), INSTRUCTION("11", nullptr), INSTRUCTION("12", nullptr), INSTRUCTION("13", nullptr), INSTRUCTION("14", nullptr), INSTRUCTION("15", nullptr), INSTRUCTION("16", nullptr), INSTRUCTION("17", nullptr), INSTRUCTION("18", nullptr), INSTRUCTION("19", nullptr), INSTRUCTION("1A", nullptr), INSTRUCTION("1B", nullptr), INSTRUCTION("1C", nullptr), INSTRUCTION("1D", nullptr), INSTRUCTION("1E", nullptr), INSTRUCTION("1F", nullptr),
    INSTRUCTION("20", nullptr), INSTRUCTION("21", nullptr), INSTRUCTION("22", nullptr), INSTRUCTION("23", nullptr), INSTRUCTION("24", nullptr), INSTRUCTION("25", nullptr), INSTRUCTION("26", nullptr), INSTRUCTION("27", nullptr), INSTRUCTION("28", nullptr), INSTRUCTION("29", nullptr), INSTRUCTION("2A", nullptr), INSTRUCTION("2B", nullptr), INSTRUCTION("2C", nullptr), INSTRUCTION("2D", nullptr), INSTRUCTION("2E", nullptr), INSTRUCTION("2F", nullptr),
    INSTRUCTION("30", nullptr), INSTRUCTION("31", nullptr), INSTRUCTION("32", nullptr), INSTRUCTION("33", nullptr), INSTRUCTION("34", nullptr), INSTRUCTION("35", nullptr), INSTRUCTION("36", nullptr), INSTRUCTION("37", nullptr), INSTRUCTION("38", nullptr), INSTRUCTION("39", nullptr), INSTRUCTION("3A", nullptr), INSTRUCTION("3B", nullptr), INSTRUCTION("3C", nullptr), INSTRUCTION("3D", nullptr), INSTRUCTION("3E", nullptr), INSTRUCTION("3F", nullptr),
    INSTRUCTION("40", nullptr), INSTRUCTION("41", nullptr), INSTRUCTION("42", SBC_implied_register_extended), INSTRUCTION("43", LD_extended_register_16_bit), INSTRUCTION("44", NEG_implied), INSTRUCTION("45", nullptr), INSTRUCTION("46", nullptr), INSTRUCTION("47", LD_implied_register_I), INSTRUCTION("48", nullptr), INSTRUCTION("49", nullptr), INSTRUCTION("4A", ADC_implied_register_extended), INSTRUCTION("4B", LD_register_extended_16_bit), INSTRUCTION("4C", nullptr), INSTRUCTION("4D", nullptr), INSTRUCTION("4E", nullptr), INSTRUCTION("4F", LD_implied_register_R),
    INSTRUCTION("50", nullptr), INSTRUCTION("51", nullptr), INSTRUCTION("52", SBC_implied_register_extended), INSTRUCTION("53", LD_extended_register_16_bit), INSTRUCTION("54", nullptr), INSTRUCTION("55", nullptr), INSTRUCTION("56", nullptr), INSTRUCTION("57", LD_register_implied_I), INSTRUCTION("58", nullptr), INSTRUCTION("59", nullptr), INSTRUCTION("5A", ADC_implied_register_extended), INSTRUCTION("5B", LD_register_extended_16_bit), INSTRUCTION("5C", nullptr), INSTRUCTION("5D", nullptr), INSTRUCTION("5E", nullptr), INSTRUCTION("5F", LD_register_implied_R),
    INSTRUCTION("60", nullptr), INSTRUCTION("61", nullptr), INSTRUCTION("62", SBC_implied_register_extended), INSTRUCTION("63", LD_extended_register_16_bit), INSTRUCTION("64", nullptr), INSTRUCTION("65", nullptr), INSTRUCTION("66", nullptr), INSTRUCTION("67", RRD_implied), INSTRUCTION("68", nullptr), INSTRUCTION("69", nullptr), INSTRUCTION("6A", ADC_implied_register_extended), INSTRUCTION("6B", LD_register_extended_16_bit), INSTRUCTION("6C", nullptr), INSTRUCTION("6D", nullptr), INSTRUCTION("6E", nullptr), INSTRUCTION("6F", RLD_implied),
    INSTRUCTION("70", nullptr), INSTRUCTION("71", nullptr), INSTRUCTION("72", SBC_implied_register_extended), INSTRUCTION("73", LD_extended_register_16_bit), INSTRUCTION("74", nullptr), INSTRUCTION("75", nullptr), INSTRUCTION("76", nullptr), INSTRUCTION("77", nullptr), INSTRUCTION("78", nullptr), INSTRUCTION("79", nullptr), INSTRUCTION("7A", ADC_implied_register_extended), INSTRUCTION("7B", LD_register_extended_16_bit), INSTRUCTION("7C", nullptr), INSTRUCTION("7D", nullptr), INSTRUCTION("7E", nullptr), INSTRUCTION("7F", nullptr),
    INSTRUCTION("80", nullptr), INSTRUCTION("81", nullptr), INSTRUCTION("82", nullptr), INSTRUCTION("83", nullptr), INSTRUCTION("84", nullptr), INSTRUCTION("85", nullptr), INSTRUCTION("86", nullptr), INSTRUCTION("87", nullptr), INSTRUCTION("88", nullptr), INSTRUCTION("89", nullptr), INSTRUCTION("8A", nullptr), INSTRUCTION("8B", nullptr), INSTRUCTION("8C", nullptr), INSTRUCTION("8D", nullptr), INSTRUCTION("8E", nullptr), INSTRUCTION("8F", nullptr),
    INSTRUCTION("90", nullptr), INSTRUCTION("91", nullptr), INSTRUCTION("92", nullptr), INSTRUCTION("93", nullptr), INSTRUCTION("94", nullptr), INSTRUCTION("95", nullptr), INSTRUCTION("96", nullptr), INSTRUCTION("97", nullptr), INSTRUCTION("98", nullptr), INSTRUCTION("99", nullptr), INSTRUCTION("9A", nullptr), INSTRUCTION("9B", nullptr), INSTRUCTION("9C", nullptr), INSTRUCTION("9D", nullptr), INSTRUCTION("9E", nullptr), INSTRUCTION("9F", nullptr),
    INSTRUCTION("A0", LDI_register_indirect_register_indirect), INSTRUCTION("A1", CPI_register_indirect), INSTRUCTION("A2", nullptr), INSTRUCTION("A3", nullptr), INSTRUCTION("A4", nullptr), INSTRUCTION("A5", nullptr), INSTRUCTION("A6", nullptr), INSTRUCTION("A7", nullptr), INSTRUCTION("A8", LDD_register_indirect_register_indirect), INSTRUCTION("A9", CPD_register_indirect), INSTRUCTION("AA", nullptr), INSTRUCTION("AB", nullptr), INSTRUCTION("AC", nullptr), INSTRUCTION("AD", nullptr), INSTRUCTION("AE", nullptr), INSTRUCTION("AF", nullptr),
    INSTRUCTION("B0", LDIR_register_indirect_register_indirect), INSTRUCTION("B1", CPIR_register_indirect), INSTRUCTION("B2", nullptr), INSTRUCTION("B3", nullptr), INSTRUCTION("B4", nullptr), INSTRUCTION("B5", nullptr), INSTRUCTION("B6", nullptr), INSTRUCTION("B7", nullptr), INSTRUCTION("B8", LDDR_register_indirect_register_indirect), INSTRUCTION("B9", CPDR_register_indirect), INSTRUCTION("BA", nullptr), INSTRUCTION("BB", nullptr), INSTRUCTION("BC", nullptr), INSTRUCTION("BD", nullptr), INSTRUCTION("BE", nullptr), INSTRUCTION("BF", nullptr),
    INSTRUCTION("C0", nullptr), INSTRUCTION("C1", nullptr), INSTRUCTION("C2", nullptr), INSTRUCTION("C3", nullptr), INSTRUCTION("C4", nullptr), INSTRUCTION("C5", nullptr), INSTRUCTION("C6", nullptr), INSTRUCTION("C7", nullptr), INSTRUCTION("C8", nullptr), INSTRUCTION("C9", nullptr), INSTRUCTION("CA", nullptr), INSTRUCTION("CB", nullptr), INSTRUCTION("CC", nullptr), INSTRUCTION("CD", nullptr), INSTRUCTION("CE", nullptr), INSTRUCTION("CF", nullptr),
    INSTRUCTION("D0", nullptr), INSTRUCTION("D1", nullptr), INSTRUCTION("D2", nullptr), INSTRUCTION("D3", nullptr), INSTRUCTION("D4", nullptr), INSTRUCTION("D5", nullptr), INSTRUCTION("D6", nullptr), INSTRUCTION("D7", nullptr), INSTRUCTION("D8", nullptr), INSTRUCTION("D9", nullptr), INSTRUCTION("DA", nullptr), INSTRUCTION("DB", nullptr), INSTRUCTION("DC", nullptr), INSTRUCTION("DD", nullptr), INSTRUCTION("DE", nullptr), INSTRUCTION("DF", nullptr),
    INSTRUCTION("E0", nullptr), INSTRUCTION("E1", nullptr), INSTRUCTION("E2", nullptr), INSTRUCTION("E3", nullptr), INSTRUCTION("E4", nullptr), INSTRUCTION("E5", nullptr), INSTRUCTION("E6", nullptr), INSTRUCTION("E7", nullptr), INSTRUCTION("E8", nullptr), INSTRUCTION("E9", nullptr), INSTRUCTION("EA", nullptr), INSTRUCTION("EB", nullptr), INSTRUCTION("EC", nullptr), INSTRUCTION("ED", nullptr), INSTRUCTION("EE", nullptr), INSTRUCTION("EF", nullptr),
    INSTRUCTION("F0", nullptr), INSTRUCTION("F1", nullptr), INSTRUCTION("F2", nullptr), INSTRUCTION("F3", nullptr), INSTRUCTION("F4", nullptr), INSTRUCTION("F5", nullptr), INSTRUCTION("F6", nullptr), INSTRUCTION("F7", nullptr), INSTRUCTION("F8", nullptr), INSTRUCTION("F9", nullptr), INSTRUCTION("FA", nullptr), INSTRUCTION("FB", nullptr), INSTRUCTION("FC", nullptr), INSTRUCTION("FD", nullptr), INSTRUCTION("FE", nullptr), INSTRUCTION("FF", nullptr)
};

constexpr std::array ix_instruction_table = {
    INSTRUCTION("00", nullptr), INSTRUCTION("01", nullptr), INSTRUCTION("02", nullptr), INSTRUCTION("03", nullptr), INSTRUCTION("04", nullptr), INSTRUCTION("05", nullptr), INSTRUCTION("06", nullptr), INSTRUCTION("07", nullptr), INSTRUCTION("08", nullptr), INSTRUCTION("09", ADD_implied_register_extended_ix), INSTRUCTION("0A", nullptr), INSTRUCTION("0B", nullptr), INSTRUCTION("0C", nullptr), INSTRUCTION("0D", nullptr), INSTRUCTION("0E", nullptr), INSTRUCTION("0F", nullptr),
    INSTRUCTION("10", nullptr), INSTRUCTION("11", nullptr), INSTRUCTION("12", nullptr), INSTRUCTION("13", nullptr), INSTRUCTION("14", nullptr), INSTRUCTION("15", nullptr), INSTRUCTION("16", nullptr), INSTRUCTION("17", nullptr), INSTRUCTION("18", nullptr), INSTRUCTION("19", ADD_implied_register_extended_ix), INSTRUCTION("1A", nullptr), INSTRUCTION("1B", nullptr), INSTRUCTION("1C", nullptr), INSTRUCTION("1D", nullptr), INSTRUCTION("1E", nullptr), INSTRUCTION("1F", nullptr),
    INSTRUCTION("20", nullptr), INSTRUCTION("21", LD_register_immediate_extended_ix), INSTRUCTION("22", LD_extended_register_ix), INSTRUCTION("23", INC_implied_register_extended_ix), INSTRUCTION("24", nullptr), INSTRUCTION("25", nullptr), INSTRUCTION("26", nullptr), INSTRUCTION("27", nullptr), INSTRUCTION("28", nullptr), INSTRUCTION("29", ADD_implied_register_extended_ix), INSTRUCTION("2A", LD_register_extended_ix), INSTRUCTION("2B", DEC_implied_register_extended_ix), INSTRUCTION("2C", nullptr), INSTRUCTION("2D", nullptr), INSTRUCTION("2E", nullptr), INSTRUCTION("2F", nullptr),
    INSTRUCTION("30", nullptr), INSTRUCTION("31", nullptr), INSTRUCTION("32", nullptr), INSTRUCTION("33", nullptr), INSTRUCTION("34", INC_implied_indexed_ix), INSTRUCTION("35", DEC_implied_indexed_ix), INSTRUCTION("36", LD_indexed_ix_immediate), INSTRUCTION("37", nullptr), INSTRUCTION("38", nullptr), INSTRUCTION("39", ADD_implied_register_extended_ix), INSTRUCTION("3A", nullptr), INSTRUCTION("3B", nullptr), INSTRUCTION("3C", nullptr), INSTRUCTION("3D", nullptr), INSTRUCTION("3E", nullptr), INSTRUCTION("3F", nullptr),
    INSTRUCTION("40", nullptr), INSTRUCTION("41", nullptr), INSTRUCTION("42", nullptr), INSTRUCTION("43", nullptr), INSTRUCTION("44", nullptr), INSTRUCTION("45", nullptr), INSTRUCTION("46", LD_register_indexed_ix), INSTRUCTION("47", nullptr), INSTRUCTION("48", nullptr), INSTRUCTION("49", nullptr), INSTRUCTION("4A", nullptr), INSTRUCTION("4B", nullptr), INSTRUCTION("4C", nullptr), INSTRUCTION("4D", nullptr), INSTRUCTION("4E", LD_register_indexed_ix), INSTRUCTION("4F", nullptr),
    INSTRUCTION("50", nullptr), INSTRUCTION("51", nullptr), INSTRUCTION("52", nullptr), INSTRUCTION("53", nullptr), INSTRUCTION("54", nullptr), INSTRUCTION("55", nullptr), INSTRUCTION("56", LD_register_indexed_ix), INSTRUCTION("57", nullptr), INSTRUCTION("58", nullptr), INSTRUCTION("59", nullptr), INSTRUCTION("5A", nullptr), INSTRUCTION("5B", nullptr), INSTRUCTION("5C", nullptr), INSTRUCTION("5D", nullptr), INSTRUCTION("5E", LD_register_indexed_ix), INSTRUCTION("5F", nullptr),
    INSTRUCTION("60", nullptr), INSTRUCTION("61", nullptr), INSTRUCTION("62", nullptr), INSTRUCTION("63", nullptr), INSTRUCTION("64", nullptr), INSTRUCTION("65", nullptr), INSTRUCTION("66", LD_register_indexed_ix), INSTRUCTION("67", nullptr), INSTRUCTION("68", nullptr), INSTRUCTION("69", nullptr), INSTRUCTION("6A", nullptr), INSTRUCTION("6B", nullptr), INSTRUCTION("6C", nullptr), INSTRUCTION("6D", nullptr), INSTRUCTION("6E", LD_register_indexed_ix), INSTRUCTION("6F", nullptr),
    INSTRUCTION("70", LD_indexed_ix_register), INSTRUCTION("71", LD_indexed_ix_register), INSTRUCTION("72", LD_indexed_ix_register), INSTRUCTION("73", LD_indexed_ix_register), INSTRUCTION("74", LD_indexed_ix_register), INSTRUCTION("75", LD_indexed_ix_register), INSTRUCTION("76", nullptr), INSTRUCTION("77", LD_indexed_ix_register), INSTRUCTION("78", nullptr), INSTRUCTION("79", nullptr), INSTRUCTION("7A", nullptr), INSTRUCTION("7B", nullptr), INSTRUCTION("7C", nullptr), INSTRUCTION("7D", nullptr), INSTRUCTION("7E", LD_register_indexed_ix), INSTRUCTION("7F", nullptr),
    INSTRUCTION("80", nullptr), INSTRUCTION("81", nullptr), INSTRUCTION("82", nullptr), INSTRUCTION("83", nullptr), INSTRUCTION("84", nullptr), INSTRUCTION("85", nullptr), INSTRUCTION("86", ADD_implied_indexed_ix), INSTRUCTION("87", nullptr), INSTRUCTION("88", nullptr), INSTRUCTION("89", nullptr), INSTRUCTION("8A", nullptr), INSTRUCTION("8B", nullptr), INSTRUCTION("8C", nullptr), INSTRUCTION("8D", nullptr), INSTRUCTION("8E", ADC_implied_indexed_ix), INSTRUCTION("8F", nullptr),
    INSTRUCTION("90", nullptr), INSTRUCTION("91", nullptr), INSTRUCTION("92", nullptr), INSTRUCTION("93", nullptr), INSTRUCTION("94", nullptr), INSTRUCTION("95", nullptr), INSTRUCTION("96", SUB_implied_indexed_ix), INSTRUCTION("97", nullptr), INSTRUCTION("98", nullptr), INSTRUCTION("99", nullptr), INSTRUCTION("9A", nullptr), INSTRUCTION("9B", nullptr), INSTRUCTION("9C", nullptr), INSTRUCTION("9D", nullptr), INSTRUCTION("9E", SBC_implied_indexed_ix), INSTRUCTION("9F", nullptr),
    INSTRUCTION("A0", nullptr), INSTRUCTION("A1", nullptr), INSTRUCTION("A2", nullptr), INSTRUCTION("A3", nullptr), INSTRUCTION("A4", nullptr), INSTRUCTION("A5", nullptr), INSTRUCTION("A6", AND_implied_indexed_ix), INSTRUCTION("A7", nullptr), INSTRUCTION("A8", nullptr), INSTRUCTION("A9", nullptr), INSTRUCTION("AA", nullptr), INSTRUCTION("AB", nullptr), INSTRUCTION("AC", nullptr), INSTRUCTION("AD", nullptr), INSTRUCTION("AE", XOR_implied_indexed_ix), INSTRUCTION("AF", nullptr),
    INSTRUCTION("B0", nullptr), INSTRUCTION("B1", nullptr), INSTRUCTION("B2", nullptr), INSTRUCTION("B3", nullptr), INSTRUCTION("B4", nullptr), INSTRUCTION("B5", nullptr), INSTRUCTION("B6", OR_implied_indexed_ix), INSTRUCTION("B7", nullptr), INSTRUCTION("B8", nullptr), INSTRUCTION("B9", nullptr), INSTRUCTION("BA", nullptr), INSTRUCTION("BB", nullptr), INSTRUCTION("BC", nullptr), INSTRUCTION("BD", nullptr), INSTRUCTION("BE", CP_implied_indexed_ix), INSTRUCTION("BF", nullptr),
    INSTRUCTION("C0", nullptr), INSTRUCTION("C1", nullptr), INSTRUCTION("C2", nullptr), INSTRUCTION("C3", nullptr), INSTRUCTION("C4", nullptr), INSTRUCTION("C5", nullptr), INSTRUCTION("C6", nullptr), INSTRUCTION("C7", nullptr), INSTRUCTION("C8", nullptr), INSTRUCTION("C9", nullptr), INSTRUCTION("CA", nullptr), INSTRUCTION("CB", ix_bit_instructions), INSTRUCTION("CC", nullptr), INSTRUCTION("CD", nullptr), INSTRUCTION("CE", nullptr), INSTRUCTION("CF", nullptr),
    INSTRUCTION("D0", nullptr), INSTRUCTION("D1", nullptr), INSTRUCTION("D2", nullptr), INSTRUCTION("D3", nullptr), INSTRUCTION("D4", nullptr), INSTRUCTION("D5", nullptr), INSTRUCTION("D6", nullptr), INSTRUCTION("D7", nullptr), INSTRUCTION("D8", nullptr), INSTRUCTION("D9", nullptr), INSTRUCTION("DA", nullptr), INSTRUCTION("DB", nullptr), INSTRUCTION("DC", nullptr), INSTRUCTION("DD", nullptr), INSTRUCTION("DE", nullptr), INSTRUCTION("DF", nullptr),
    INSTRUCTION("E0", nullptr), INSTRUCTION("E1", POP_register_indirect_register_ix), INSTRUCTION("E2", nullptr), INSTRUCTION("E3", EX_register_indirect_implied_ix), INSTRUCTION("E4", nullptr), INSTRUCTION("E5", PUSH_register_indirect_register_ix), INSTRUCTION("E6", nullptr), INSTRUCTION("E7", nullptr), INSTRUCTION("E8", nullptr), INSTRUCTION("E9", JP_implict_ix), INSTRUCTION("EA", nullptr), INSTRUCTION("EB", nullptr), INSTRUCTION("EC", nullptr), INSTRUCTION("ED", nullptr), INSTRUCTION("EE", nullptr), INSTRUCTION("EF", nullptr),
    INSTRUCTION("F0", nullptr), INSTRUCTION("F1", nullptr), INSTRUCTION("F2", nullptr), INSTRUCTION("F3", nullptr), INSTRUCTION("F4", nullptr), INSTRUCTION("F5", nullptr), INSTRUCTION("F6", nullptr), INSTRUCTION("F7", nullptr), INSTRUCTION("F8", nullptr), INSTRUCTION("F9", LD_register_register_ix), INSTRUCTION("FA", nullptr), INSTRUCTION("FB", nullptr), INSTRUCTION("FC", nullptr), INSTRUCTION("FD", nullptr), INSTRUCTION("FE", nullptr), INSTRUCTION("FF", nullptr)
};

constexpr std::array iy_instruction_table = {
    INSTRUCTION("00", nullptr ), INSTRUCTION("01", nullptr ), INSTRUCTION("02", nullptr ), INSTRUCTION("03", nullptr ), INSTRUCTION("04", nullptr ), INSTRUCTION("05", nullptr ), INSTRUCTION("06", nullptr ), INSTRUCTION("07", nullptr ), INSTRUCTION("08", nullptr ), INSTRUCTION("09", ADD_implied_register_extended_iy ), INSTRUCTION("0A", nullptr ), INSTRUCTION("0B", nullptr ), INSTRUCTION("0C", nullptr ), INSTRUCTION("0D", nullptr ), INSTRUCTION("0E", nullptr ), INSTRUCTION("0F", nullptr ),
    INSTRUCTION("10", nullptr ), INSTRUCTION("11", nullptr ), INSTRUCTION("12", nullptr ), INSTRUCTION("13", nullptr ), INSTRUCTION("14", nullptr ), INSTRUCTION("15", nullptr ), INSTRUCTION("16", nullptr ), INSTRUCTION("17", nullptr ), INSTRUCTION("18", nullptr ), INSTRUCTION("19", ADD_implied_register_extended_iy ), INSTRUCTION("1A", nullptr ), INSTRUCTION("1B", nullptr ), INSTRUCTION("1C", nullptr ), INSTRUCTION("1D", nullptr ), INSTRUCTION("1E", nullptr ), INSTRUCTION("1F", nullptr ),
    INSTRUCTION("20", nullptr ), INSTRUCTION("21", LD_register_immediate_extended_iy ), INSTRUCTION("22", LD_extended_register_iy ), INSTRUCTION("23", INC_implied_register_extended_iy ), INSTRUCTION("24", nullptr ), INSTRUCTION("25", nullptr ), INSTRUCTION("26", nullptr ), INSTRUCTION("27", nullptr ), INSTRUCTION("28", nullptr ), INSTRUCTION("29", ADD_implied_register_extended_iy ), INSTRUCTION("2A", LD_register_extended_iy ), INSTRUCTION("2B", DEC_implied_register_extended_iy ), INSTRUCTION("2C", nullptr ), INSTRUCTION("2D", nullptr ), INSTRUCTION("2E", nullptr ), INSTRUCTION("2F", nullptr ),
    INSTRUCTION("30", nullptr ), INSTRUCTION("31", nullptr ), INSTRUCTION("32", nullptr ), INSTRUCTION("33", nullptr ), INSTRUCTION("34", INC_implied_indexed_iy ), INSTRUCTION("35", DEC_implied_indexed_iy ), INSTRUCTION("36", LD_indexed_iy_immediate ), INSTRUCTION("37", nullptr ), INSTRUCTION("38", nullptr ), INSTRUCTION("39", ADD_implied_register_extended_iy ), INSTRUCTION("3A", nullptr ), INSTRUCTION("3B", nullptr ), INSTRUCTION("3C", nullptr ), INSTRUCTION("3D", nullptr ), INSTRUCTION("3E", nullptr ), INSTRUCTION("3F", nullptr ),
    INSTRUCTION("40", nullptr ), INSTRUCTION("41", nullptr ), INSTRUCTION("42", nullptr ), INSTRUCTION("43", nullptr ), INSTRUCTION("44", nullptr ), INSTRUCTION("45", nullptr ), INSTRUCTION("46", LD_register_indexed_iy ), INSTRUCTION("47", nullptr ), INSTRUCTION("48", nullptr ), INSTRUCTION("49", nullptr ), INSTRUCTION("4A", nullptr ), INSTRUCTION("4B", nullptr ), INSTRUCTION("4C", nullptr ), INSTRUCTION("4D", nullptr ), INSTRUCTION("4E", LD_register_indexed_iy ), INSTRUCTION("4F", nullptr ),
    INSTRUCTION("50", nullptr ), INSTRUCTION("51", nullptr ), INSTRUCTION("52", nullptr ), INSTRUCTION("53", nullptr ), INSTRUCTION("54", nullptr ), INSTRUCTION("55", nullptr ), INSTRUCTION("56", LD_register_indexed_iy ), INSTRUCTION("57", nullptr ), INSTRUCTION("58", nullptr ), INSTRUCTION("59", nullptr ), INSTRUCTION("5A", nullptr ), INSTRUCTION("5B", nullptr ), INSTRUCTION("5C", nullptr ), INSTRUCTION("5D", nullptr ), INSTRUCTION("5E", LD_register_indexed_iy ), INSTRUCTION("5F", nullptr ),
    INSTRUCTION("60", nullptr ), INSTRUCTION("61", nullptr ), INSTRUCTION("62", nullptr ), INSTRUCTION("63", nullptr ), INSTRUCTION("64", nullptr ), INSTRUCTION("65", nullptr ), INSTRUCTION("66", LD_register_indexed_iy ), INSTRUCTION("67", nullptr ), INSTRUCTION("68", nullptr ), INSTRUCTION("69", nullptr ), INSTRUCTION("6A", nullptr ), INSTRUCTION("6B", nullptr ), INSTRUCTION("6C", nullptr ), INSTRUCTION("6D", nullptr ), INSTRUCTION("6E", LD_register_indexed_iy ), INSTRUCTION("6F", nullptr ),
    INSTRUCTION("70", LD_indexed_iy_register ), INSTRUCTION("71", LD_indexed_iy_register ), INSTRUCTION("72", LD_indexed_iy_register ), INSTRUCTION("73", LD_indexed_iy_register ), INSTRUCTION("74", LD_indexed_iy_register ), INSTRUCTION("75", LD_indexed_iy_register ), INSTRUCTION("76", nullptr ), INSTRUCTION("77", LD_indexed_iy_register ), INSTRUCTION("78", nullptr ), INSTRUCTION("79", nullptr ), INSTRUCTION("7A", nullptr ), INSTRUCTION("7B", nullptr ), INSTRUCTION("7C", nullptr ), INSTRUCTION("7D", nullptr ), INSTRUCTION("7E", LD_register_indexed_iy ), INSTRUCTION("7F", nullptr ),
    INSTRUCTION("80", nullptr ), INSTRUCTION("81", nullptr ), INSTRUCTION("82", nullptr ), INSTRUCTION("83", nullptr ), INSTRUCTION("84", nullptr ), INSTRUCTION("85", nullptr ), INSTRUCTION("86", ADD_implied_indexed_iy ), INSTRUCTION("87", nullptr ), INSTRUCTION("88", nullptr ), INSTRUCTION("89", nullptr ), INSTRUCTION("8A", nullptr ), INSTRUCTION("8B", nullptr ), INSTRUCTION("8C", nullptr ), INSTRUCTION("8D", nullptr ), INSTRUCTION("8E", ADC_implied_indexed_iy ), INSTRUCTION("8F", nullptr ),
    INSTRUCTION("90", nullptr ), INSTRUCTION("91", nullptr ), INSTRUCTION("92", nullptr ), INSTRUCTION("93", nullptr ), INSTRUCTION("94", nullptr ), INSTRUCTION("95", nullptr ), INSTRUCTION("96", SUB_implied_indexed_iy ), INSTRUCTION("97", nullptr ), INSTRUCTION("98", nullptr ), INSTRUCTION("99", nullptr ), INSTRUCTION("9A", nullptr ), INSTRUCTION("9B", nullptr ), INSTRUCTION("9C", nullptr ), INSTRUCTION("9D", nullptr ), INSTRUCTION("9E", SBC_implied_indexed_iy ), INSTRUCTION("9F", nullptr ),
    INSTRUCTION("A0", nullptr ), INSTRUCTION("A1", nullptr ), INSTRUCTION("A2", nullptr ), INSTRUCTION("A3", nullptr ), INSTRUCTION("A4", nullptr ), INSTRUCTION("A5", nullptr ), INSTRUCTION("A6", AND_implied_indexed_iy ), INSTRUCTION("A7", nullptr ), INSTRUCTION("A8", nullptr ), INSTRUCTION("A9", nullptr ), INSTRUCTION("AA", nullptr ), INSTRUCTION("AB", nullptr ), INSTRUCTION("AC", nullptr ), INSTRUCTION("AD", nullptr ), INSTRUCTION("AE", XOR_implied_indexed_iy ), INSTRUCTION("AF", nullptr ),
    INSTRUCTION("B0", nullptr ), INSTRUCTION("B1", nullptr ), INSTRUCTION("B2", nullptr ), INSTRUCTION("B3", nullptr ), INSTRUCTION("B4", nullptr ), INSTRUCTION("B5", nullptr ), INSTRUCTION("B6", OR_implied_indexed_iy ), INSTRUCTION("B7", nullptr ), INSTRUCTION("B8", nullptr ), INSTRUCTION("B9", nullptr ), INSTRUCTION("BA", nullptr ), INSTRUCTION("BB", nullptr ), INSTRUCTION("BC", nullptr ), INSTRUCTION("BD", nullptr ), INSTRUCTION("BE", CP_implied_indexed_iy ), INSTRUCTION("BF", nullptr ),
    INSTRUCTION("C0", nullptr ), INSTRUCTION("C1", nullptr ), INSTRUCTION("C2", nullptr ), INSTRUCTION("C3", nullptr ), INSTRUCTION("C4", nullptr ), INSTRUCTION("C5", nullptr ), INSTRUCTION("C6", nullptr ), INSTRUCTION("C7", nullptr ), INSTRUCTION("C8", nullptr ), INSTRUCTION("C9", nullptr ), INSTRUCTION("CA", nullptr ), INSTRUCTION("CB", iy_bit_instructions ), INSTRUCTION("CC", nullptr ), INSTRUCTION("CD", nullptr ), INSTRUCTION("CE", nullptr ), INSTRUCTION("CF", nullptr ),
    INSTRUCTION("D0", nullptr ), INSTRUCTION("D1", nullptr ), INSTRUCTION("D2", nullptr ), INSTRUCTION("D3", nullptr ), INSTRUCTION("D4", nullptr ), INSTRUCTION("D5", nullptr ), INSTRUCTION("D6", nullptr ), INSTRUCTION("D7", nullptr ), INSTRUCTION("D8", nullptr ), INSTRUCTION("D9", nullptr ), INSTRUCTION("DA", nullptr ), INSTRUCTION("DB", nullptr ), INSTRUCTION("DC", nullptr ), INSTRUCTION("DD", nullptr ), INSTRUCTION("DE", nullptr ), INSTRUCTION("DF", nullptr ),
    INSTRUCTION("E0", nullptr ), INSTRUCTION("E1", POP_register_indirect_register_iy ), INSTRUCTION("E2", nullptr ), INSTRUCTION("E3", EX_register_indirect_implied_iy ), INSTRUCTION("E4", nullptr ), INSTRUCTION("E5", PUSH_register_indirect_register_iy ), INSTRUCTION("E6", nullptr ), INSTRUCTION("E7", nullptr ), INSTRUCTION("E8", nullptr ), INSTRUCTION("E9", JP_implict_iy ), INSTRUCTION("EA", nullptr ), INSTRUCTION("EB", nullptr ), INSTRUCTION("EC", nullptr ), INSTRUCTION("ED", nullptr ), INSTRUCTION("EE", nullptr ), INSTRUCTION("EF", nullptr ),
    INSTRUCTION("F0", nullptr ), INSTRUCTION("F1", nullptr ), INSTRUCTION("F2", nullptr ), INSTRUCTION("F3", nullptr ), INSTRUCTION("F4", nullptr ), INSTRUCTION("F5", nullptr ), INSTRUCTION("F6", nullptr ), INSTRUCTION("F7", nullptr ), INSTRUCTION("F8", nullptr ), INSTRUCTION("F9", LD_register_register_iy ), INSTRUCTION("FA", nullptr ), INSTRUCTION("FB", nullptr ), INSTRUCTION("FC", nullptr ), INSTRUCTION("FD", nullptr ), INSTRUCTION("FE", nullptr ), INSTRUCTION("FF", nullptr )
};

constexpr std::array bit_instruction_table = {
    INSTRUCTION("00", RLC_implied ), INSTRUCTION("01", RLC_implied ), INSTRUCTION("02", RLC_implied ), INSTRUCTION("03", RLC_implied ), INSTRUCTION("04", RLC_implied ), INSTRUCTION("05", RLC_implied ), INSTRUCTION("06", RLC_indirect ), INSTRUCTION("07", RLC_implied ), INSTRUCTION("08", RRC_implied ), INSTRUCTION("09", RRC_implied ), INSTRUCTION("0A", RRC_implied ), INSTRUCTION("0B", RRC_implied ), INSTRUCTION("0C", RRC_implied ), INSTRUCTION("0D", RRC_implied ), INSTRUCTION("0E", RRC_indirect ), INSTRUCTION("0F", RRC_implied ),
    INSTRUCTION("10", RL_implied ), INSTRUCTION("11", RL_implied ), INSTRUCTION("12", RL_implied ), INSTRUCTION("13", RL_implied ), INSTRUCTION("14", RL_implied ), INSTRUCTION("15", RL_implied ), INSTRUCTION("16", RL_indirect ), INSTRUCTION("17", RL_implied ), INSTRUCTION("18", RR_implied ), INSTRUCTION("19", RR_implied  ), INSTRUCTION("1A", RR_implied  ), INSTRUCTION("1B", RR_implied  ), INSTRUCTION("1C", RR_implied  ), INSTRUCTION("1D", RR_implied  ), INSTRUCTION("1E", RR_indirect  ), INSTRUCTION("1F", RR_implied  ),
    INSTRUCTION("20", SLA_implied ), INSTRUCTION("21", SLA_implied ), INSTRUCTION("22", SLA_implied ), INSTRUCTION("23", SLA_implied ), INSTRUCTION("24", SLA_implied ), INSTRUCTION("25", SLA_implied ), INSTRUCTION("26", SLA_indirect ), INSTRUCTION("27", SLA_implied ), INSTRUCTION("28", SRA_implied ), INSTRUCTION("29", SRA_implied ), INSTRUCTION("2A", SRA_implied ), INSTRUCTION("2B", SRA_implied ), INSTRUCTION("2C", SRA_implied ), INSTRUCTION("2D", SRA_implied ), INSTRUCTION("2E", SRA_indirect ), INSTRUCTION("2F", SRA_implied ),
    INSTRUCTION("30", nullptr ), INSTRUCTION("31", nullptr ), INSTRUCTION("32", nullptr ), INSTRUCTION("33", nullptr ), INSTRUCTION("34", nullptr ), INSTRUCTION("35", nullptr ), INSTRUCTION("36", nullptr ), INSTRUCTION("37", nullptr ), INSTRUCTION("38", SRL_implied ), INSTRUCTION("39", SRL_implied ), INSTRUCTION("3A", SRL_implied ), INSTRUCTION("3B", SRL_implied ), INSTRUCTION("3C", SRL_implied ), INSTRUCTION("3D", SRL_implied ), INSTRUCTION("3E", SRL_indirect ), INSTRUCTION("3F", SRL_implied ),
    INSTRUCTION("40", BIT_implied ), INSTRUCTION("41", BIT_implied ), INSTRUCTION("42", BIT_implied ), INSTRUCTION("43", BIT_implied ), INSTRUCTION("44", BIT_implied ), INSTRUCTION("45", BIT_implied ), INSTRUCTION("46", BIT_indirect ), INSTRUCTION("47", BIT_implied ), INSTRUCTION("48", BIT_implied ), INSTRUCTION("49", BIT_implied ), INSTRUCTION("4A", BIT_implied ), INSTRUCTION("4B", BIT_implied ), INSTRUCTION("4C", BIT_implied ), INSTRUCTION("4D", BIT_implied ), INSTRUCTION("4E", BIT_indirect ), INSTRUCTION("4F", BIT_implied ),
    INSTRUCTION("50", BIT_implied ), INSTRUCTION("51", BIT_implied ), INSTRUCTION("52", BIT_implied ), INSTRUCTION("53", BIT_implied ), INSTRUCTION("54", BIT_implied ), INSTRUCTION("55", BIT_implied ), INSTRUCTION("56", BIT_indirect ), INSTRUCTION("57", BIT_implied ), INSTRUCTION("58", BIT_implied ), INSTRUCTION("59", BIT_implied ), INSTRUCTION("5A", BIT_implied ), INSTRUCTION("5B", BIT_implied ), INSTRUCTION("5C", BIT_implied ), INSTRUCTION("5D", BIT_implied ), INSTRUCTION("5E", BIT_indirect ), INSTRUCTION("5F", BIT_implied ),
    INSTRUCTION("60", BIT_implied ), INSTRUCTION("61", BIT_implied ), INSTRUCTION("62", BIT_implied ), INSTRUCTION("63", BIT_implied ), INSTRUCTION("64", BIT_implied ), INSTRUCTION("65", BIT_implied ), INSTRUCTION("66", BIT_indirect ), INSTRUCTION("67", BIT_implied ), INSTRUCTION("68", BIT_implied ), INSTRUCTION("69", BIT_implied ), INSTRUCTION("6A", BIT_implied ), INSTRUCTION("6B", BIT_implied ), INSTRUCTION("6C", BIT_implied ), INSTRUCTION("6D", BIT_implied ), INSTRUCTION("6E", BIT_indirect ), INSTRUCTION("6F", BIT_implied ),
    INSTRUCTION("70", BIT_implied ), INSTRUCTION("71", BIT_implied ), INSTRUCTION("72", BIT_implied ), INSTRUCTION("73", BIT_implied ), INSTRUCTION("74", BIT_implied ), INSTRUCTION("75", BIT_implied ), INSTRUCTION("76", BIT_indirect ), INSTRUCTION("77", BIT_implied ), INSTRUCTION("78", BIT_implied ), INSTRUCTION("79", BIT_implied ), INSTRUCTION("7A", BIT_implied ), INSTRUCTION("7B", BIT_implied ), INSTRUCTION("7C", BIT_implied ), INSTRUCTION("7D", BIT_implied ), INSTRUCTION("7E", BIT_indirect ), INSTRUCTION("7F", BIT_implied ),
    INSTRUCTION("80", RES_implied ), INSTRUCTION("81", RES_implied ), INSTRUCTION("82", RES_implied ), INSTRUCTION("83", RES_implied ), INSTRUCTION("84", RES_implied ), INSTRUCTION("85", RES_implied ), INSTRUCTION("86", RES_indirect ), INSTRUCTION("87", RES_implied ), INSTRUCTION("88", RES_implied ), INSTRUCTION("89", RES_implied ), INSTRUCTION("8A", RES_implied ), INSTRUCTION("8B", RES_implied ), INSTRUCTION("8C", RES_implied ), INSTRUCTION("8D", RES_implied ), INSTRUCTION("8E", RES_indirect ), INSTRUCTION("8F", RES_implied ),
    INSTRUCTION("90", RES_implied ), INSTRUCTION("91", RES_implied ), INSTRUCTION("92", RES_implied ), INSTRUCTION("93", RES_implied ), INSTRUCTION("94", RES_implied ), INSTRUCTION("95", RES_implied ), INSTRUCTION("96", RES_indirect ), INSTRUCTION("97", RES_implied ), INSTRUCTION("98", RES_implied ), INSTRUCTION("99", RES_implied ), INSTRUCTION("9A", RES_implied ), INSTRUCTION("9B", RES_implied ), INSTRUCTION("9C", RES_implied ), INSTRUCTION("9D", RES_implied ), INSTRUCTION("9E", RES_indirect ), INSTRUCTION("9F", RES_implied ),
    INSTRUCTION("A0", RES_implied ), INSTRUCTION("A1", RES_implied ), INSTRUCTION("A2", RES_implied ), INSTRUCTION("A3", RES_implied ), INSTRUCTION("A4", RES_implied ), INSTRUCTION("A5", RES_implied ), INSTRUCTION("A6", RES_indirect ), INSTRUCTION("A7", RES_implied ), INSTRUCTION("A8", RES_implied ), INSTRUCTION("A9", RES_implied ), INSTRUCTION("AA", RES_implied ), INSTRUCTION("AB", RES_implied ), INSTRUCTION("AC", RES_implied ), INSTRUCTION("AD", RES_implied ), INSTRUCTION("AE", RES_indirect ), INSTRUCTION("AF", RES_implied ),
    INSTRUCTION("B0", RES_implied ), INSTRUCTION("B1", RES_implied ), INSTRUCTION("B2", RES_implied ), INSTRUCTION("B3", RES_implied ), INSTRUCTION("B4", RES_implied ), INSTRUCTION("B5", RES_implied ), INSTRUCTION("B6", RES_indirect ), INSTRUCTION("B7", RES_implied ), INSTRUCTION("B8", RES_implied ), INSTRUCTION("B9", RES_implied ), INSTRUCTION("BA", RES_implied ), INSTRUCTION("BB", RES_implied ), INSTRUCTION("BC", RES_implied ), INSTRUCTION("BD", RES_implied ), INSTRUCTION("BE", RES_indirect ), INSTRUCTION("BF", RES_implied ),
    INSTRUCTION("C0", SET_implied ), INSTRUCTION("C1", SET_implied ), INSTRUCTION("C2", SET_implied ), INSTRUCTION("C3", SET_implied ), INSTRUCTION("C4", SET_implied ), INSTRUCTION("C5", SET_implied ), INSTRUCTION("C6", SET_indirect ), INSTRUCTION("C7", SET_implied ), INSTRUCTION("C8", SET_implied ), INSTRUCTION("C9", SET_implied ), INSTRUCTION("CA", SET_implied ), INSTRUCTION("CB", SET_implied ), INSTRUCTION("CC", SET_implied ), INSTRUCTION("CD", SET_implied ), INSTRUCTION("CE", SET_indirect ), INSTRUCTION("CF", SET_implied ),
    INSTRUCTION("D0", SET_implied ), INSTRUCTION("D1", SET_implied ), INSTRUCTION("D2", SET_implied ), INSTRUCTION("D3", SET_implied ), INSTRUCTION("D4", SET_implied ), INSTRUCTION("D5", SET_implied ), INSTRUCTION("D6", SET_indirect ), INSTRUCTION("D7", SET_implied ), INSTRUCTION("D8", SET_implied ), INSTRUCTION("D9", SET_implied ), INSTRUCTION("DA", SET_implied ), INSTRUCTION("DB", SET_implied ), INSTRUCTION("DC", SET_implied ), INSTRUCTION("DD", SET_implied ), INSTRUCTION("DE", SET_indirect ), INSTRUCTION("DF", SET_implied ),
    INSTRUCTION("E0", SET_implied ), INSTRUCTION("E1", SET_implied ), INSTRUCTION("E2", SET_implied ), INSTRUCTION("E3", SET_implied ), INSTRUCTION("E4", SET_implied ), INSTRUCTION("E5", SET_implied ), INSTRUCTION("E6", SET_indirect ), INSTRUCTION("E7", SET_implied ), INSTRUCTION("E8", SET_implied ), INSTRUCTION("E9", SET_implied ), INSTRUCTION("EA", SET_implied ), INSTRUCTION("EB", SET_implied ), INSTRUCTION("EC", SET_implied ), INSTRUCTION("ED", SET_implied ), INSTRUCTION("EE", SET_indirect ), INSTRUCTION("EF", SET_implied ),
    INSTRUCTION("F0", SET_implied ), INSTRUCTION("F1", SET_implied ), INSTRUCTION("F2", SET_implied ), INSTRUCTION("F3", SET_implied ), INSTRUCTION("F4", SET_implied ), INSTRUCTION("F5", SET_implied ), INSTRUCTION("F6", SET_indirect ), INSTRUCTION("F7", SET_implied ), INSTRUCTION("F8", SET_implied ), INSTRUCTION("F9", SET_implied ), INSTRUCTION("FA", SET_implied ), INSTRUCTION("FB", SET_implied ), INSTRUCTION("FC", SET_implied ), INSTRUCTION("FD", SET_implied ), INSTRUCTION("FE", SET_indirect ), INSTRUCTION("FF", SET_implied )
};

constexpr std::array ix_bit_instruction_table = {
    INSTRUCTION("00", nullptr ), INSTRUCTION("01", nullptr ), INSTRUCTION("02", nullptr ), INSTRUCTION("03", nullptr ), INSTRUCTION("04", nullptr ), INSTRUCTION("05", nullptr ), INSTRUCTION("06", RLC_indexed_ix ), INSTRUCTION("07", nullptr ), INSTRUCTION("08", nullptr ), INSTRUCTION("09", nullptr ), INSTRUCTION("0A", nullptr ), INSTRUCTION("0B", nullptr ), INSTRUCTION("0C", nullptr ), INSTRUCTION("0D", nullptr ), INSTRUCTION("0E", RRC_indexed_ix), INSTRUCTION("0F", nullptr ),
    INSTRUCTION("10", nullptr ), INSTRUCTION("11", nullptr ), INSTRUCTION("12", nullptr ), INSTRUCTION("13", nullptr ), INSTRUCTION("14", nullptr ), INSTRUCTION("15", nullptr ), INSTRUCTION("16", RL_indexed_ix ), INSTRUCTION("17", nullptr ), INSTRUCTION("18", nullptr ), INSTRUCTION("19", nullptr ), INSTRUCTION("1A", nullptr ), INSTRUCTION("1B", nullptr ), INSTRUCTION("1C", nullptr ), INSTRUCTION("1D", nullptr ), INSTRUCTION("1E", RR_indexed_ix ), INSTRUCTION("1F", nullptr ),
    INSTRUCTION("20", nullptr ), INSTRUCTION("21", nullptr ), INSTRUCTION("22", nullptr ), INSTRUCTION("23", nullptr ), INSTRUCTION("24", nullptr ), INSTRUCTION("25", nullptr ), INSTRUCTION("26", SLA_indexed_ix ), INSTRUCTION("27", nullptr ), INSTRUCTION("28", nullptr ), INSTRUCTION("29", nullptr ), INSTRUCTION("2A", nullptr ), INSTRUCTION("2B", nullptr ), INSTRUCTION("2C", nullptr ), INSTRUCTION("2D", nullptr ), INSTRUCTION("2E", SRA_indexed_ix ), INSTRUCTION("2F", nullptr ),
    INSTRUCTION("30", nullptr ), INSTRUCTION("31", nullptr ), INSTRUCTION("32", nullptr ), INSTRUCTION("33", nullptr ), INSTRUCTION("34", nullptr ), INSTRUCTION("35", nullptr ), INSTRUCTION("36", nullptr ), INSTRUCTION("37", nullptr ), INSTRUCTION("38", nullptr ), INSTRUCTION("39", nullptr ), INSTRUCTION("3A", nullptr ), INSTRUCTION("3B", nullptr ), INSTRUCTION("3C", nullptr ), INSTRUCTION("3D", nullptr ), INSTRUCTION("3E", SRL_indexed_ix ), INSTRUCTION("3F", nullptr ),
    INSTRUCTION("40", nullptr ), INSTRUCTION("41", nullptr ), INSTRUCTION("42", nullptr ), INSTRUCTION("43", nullptr ), INSTRUCTION("44", nullptr ), INSTRUCTION("45", nullptr ), INSTRUCTION("46", BIT_indexed_ix ), INSTRUCTION("47", nullptr ), INSTRUCTION("48", nullptr ), INSTRUCTION("49", nullptr ), INSTRUCTION("4A", nullptr ), INSTRUCTION("4B", nullptr ), INSTRUCTION("4C", nullptr ), INSTRUCTION("4D", nullptr ), INSTRUCTION("4E", BIT_indexed_ix ), INSTRUCTION("4F", nullptr ),
    INSTRUCTION("50", nullptr ), INSTRUCTION("51", nullptr ), INSTRUCTION("52", nullptr ), INSTRUCTION("53", nullptr ), INSTRUCTION("54", nullptr ), INSTRUCTION("55", nullptr ), INSTRUCTION("56", BIT_indexed_ix ), INSTRUCTION("57", nullptr ), INSTRUCTION("58", nullptr ), INSTRUCTION("59", nullptr ), INSTRUCTION("5A", nullptr ), INSTRUCTION("5B", nullptr ), INSTRUCTION("5C", nullptr ), INSTRUCTION("5D", nullptr ), INSTRUCTION("5E", BIT_indexed_ix ), INSTRUCTION("5F", nullptr ),
    INSTRUCTION("60", nullptr ), INSTRUCTION("61", nullptr ), INSTRUCTION("62", nullptr ), INSTRUCTION("63", nullptr ), INSTRUCTION("64", nullptr ), INSTRUCTION("65", nullptr ), INSTRUCTION("66", BIT_indexed_ix ), INSTRUCTION("67", nullptr ), INSTRUCTION("68", nullptr ), INSTRUCTION("69", nullptr ), INSTRUCTION("6A", nullptr ), INSTRUCTION("6B", nullptr ), INSTRUCTION("6C", nullptr ), INSTRUCTION("6D", nullptr ), INSTRUCTION("6E", BIT_indexed_ix ), INSTRUCTION("6F", nullptr ),
    INSTRUCTION("70", nullptr ), INSTRUCTION("71", nullptr ), INSTRUCTION("72", nullptr ), INSTRUCTION("73", nullptr ), INSTRUCTION("74", nullptr ), INSTRUCTION("75", nullptr ), INSTRUCTION("76", BIT_indexed_ix ), INSTRUCTION("77", nullptr ), INSTRUCTION("78", nullptr ), INSTRUCTION("79", nullptr ), INSTRUCTION("7A", nullptr ), INSTRUCTION("7B", nullptr ), INSTRUCTION("7C", nullptr ), INSTRUCTION("7D", nullptr ), INSTRUCTION("7E", BIT_indexed_ix ), INSTRUCTION("7F", nullptr ),
    INSTRUCTION("80", nullptr ), INSTRUCTION("81", nullptr ), INSTRUCTION("82", nullptr ), INSTRUCTION("83", nullptr ), INSTRUCTION("84", nullptr ), INSTRUCTION("85", nullptr ), INSTRUCTION("86", RES_indexed_ix ), INSTRUCTION("87", nullptr ), INSTRUCTION("88", nullptr ), INSTRUCTION("89", nullptr ), INSTRUCTION("8A", nullptr ), INSTRUCTION("8B", nullptr ), INSTRUCTION("8C", nullptr ), INSTRUCTION("8D", nullptr ), INSTRUCTION("8E", RES_indexed_ix ), INSTRUCTION("8F", nullptr ),
    INSTRUCTION("90", nullptr ), INSTRUCTION("91", nullptr ), INSTRUCTION("92", nullptr ), INSTRUCTION("93", nullptr ), INSTRUCTION("94", nullptr ), INSTRUCTION("95", nullptr ), INSTRUCTION("96", RES_indexed_ix ), INSTRUCTION("97", nullptr ), INSTRUCTION("98", nullptr ), INSTRUCTION("99", nullptr ), INSTRUCTION("9A", nullptr ), INSTRUCTION("9B", nullptr ), INSTRUCTION("9C", nullptr ), INSTRUCTION("9D", nullptr ), INSTRUCTION("9E", RES_indexed_ix ), INSTRUCTION("9F", nullptr ),
    INSTRUCTION("A0", nullptr ), INSTRUCTION("A1", nullptr ), INSTRUCTION("A2", nullptr ), INSTRUCTION("A3", nullptr ), INSTRUCTION("A4", nullptr ), INSTRUCTION("A5", nullptr ), INSTRUCTION("A6", RES_indexed_ix ), INSTRUCTION("A7", nullptr ), INSTRUCTION("A8", nullptr ), INSTRUCTION("A9", nullptr ), INSTRUCTION("AA", nullptr ), INSTRUCTION("AB", nullptr ), INSTRUCTION("AC", nullptr ), INSTRUCTION("AD", nullptr ), INSTRUCTION("AE", RES_indexed_ix ), INSTRUCTION("AF", nullptr ),
    INSTRUCTION("B0", nullptr ), INSTRUCTION("B1", nullptr ), INSTRUCTION("B2", nullptr ), INSTRUCTION("B3", nullptr ), INSTRUCTION("B4", nullptr ), INSTRUCTION("B5", nullptr ), INSTRUCTION("B6", RES_indexed_ix ), INSTRUCTION("B7", nullptr ), INSTRUCTION("B8", nullptr ), INSTRUCTION("B9", nullptr ), INSTRUCTION("BA", nullptr ), INSTRUCTION("BB", nullptr ), INSTRUCTION("BC", nullptr ), INSTRUCTION("BD", nullptr ), INSTRUCTION("BE", RES_indexed_ix ), INSTRUCTION("BF", nullptr ),
    INSTRUCTION("C0", nullptr ), INSTRUCTION("C1", nullptr ), INSTRUCTION("C2", nullptr ), INSTRUCTION("C3", nullptr ), INSTRUCTION("C4", nullptr ), INSTRUCTION("C5", nullptr ), INSTRUCTION("C6", SET_indexed_ix ), INSTRUCTION("C7", nullptr ), INSTRUCTION("C8", nullptr ), INSTRUCTION("C9", nullptr ), INSTRUCTION("CA", nullptr ), INSTRUCTION("CB", nullptr ), INSTRUCTION("CC", nullptr ), INSTRUCTION("CD", nullptr ), INSTRUCTION("CE", SET_indexed_ix ), INSTRUCTION("CF", nullptr ),
    INSTRUCTION("D0", nullptr ), INSTRUCTION("D1", nullptr ), INSTRUCTION("D2", nullptr ), INSTRUCTION("D3", nullptr ), INSTRUCTION("D4", nullptr ), INSTRUCTION("D5", nullptr ), INSTRUCTION("D6", SET_indexed_ix ), INSTRUCTION("D7", nullptr ), INSTRUCTION("D8", nullptr ), INSTRUCTION("D9", nullptr ), INSTRUCTION("DA", nullptr ), INSTRUCTION("DB", nullptr ), INSTRUCTION("DC", nullptr ), INSTRUCTION("DD", nullptr ), INSTRUCTION("DE", SET_indexed_ix ), INSTRUCTION("DF", nullptr ),
    INSTRUCTION("E0", nullptr ), INSTRUCTION("E1", nullptr ), INSTRUCTION("E2", nullptr ), INSTRUCTION("E3", nullptr ), INSTRUCTION("E4", nullptr ), INSTRUCTION("E5", nullptr ), INSTRUCTION("E6", SET_indexed_ix ), INSTRUCTION("E7", nullptr ), INSTRUCTION("E8", nullptr ), INSTRUCTION("E9", nullptr ), INSTRUCTION("EA", nullptr ), INSTRUCTION("EB", nullptr ), INSTRUCTION("EC", nullptr ), INSTRUCTION("ED", nullptr ), INSTRUCTION("EE", SET_indexed_ix ), INSTRUCTION("EF", nullptr ),
    INSTRUCTION("F0", nullptr ), INSTRUCTION("F1", nullptr ), INSTRUCTION("F2", nullptr ), INSTRUCTION("F3", nullptr ), INSTRUCTION("F4", nullptr ), INSTRUCTION("F5", nullptr ), INSTRUCTION("F6", SET_indexed_ix ), INSTRUCTION("F7", nullptr ), INSTRUCTION("F8", nullptr ), INSTRUCTION("F9", nullptr ), INSTRUCTION("FA", nullptr ), INSTRUCTION("FB", nullptr ), INSTRUCTION("FC", nullptr ), INSTRUCTION("FD", nullptr ), INSTRUCTION("FE", SET_indexed_ix ), INSTRUCTION("FF", nullptr )
};

constexpr std::array iy_bit_instruction_table = {
    INSTRUCTION("00", nullptr ), INSTRUCTION("01", nullptr ), INSTRUCTION("02", nullptr ), INSTRUCTION("03", nullptr ), INSTRUCTION("04", nullptr ), INSTRUCTION("05", nullptr ), INSTRUCTION("06", RLC_indexed_iy ), INSTRUCTION("07", nullptr ), INSTRUCTION("08", nullptr ), INSTRUCTION("09", nullptr ), INSTRUCTION("0A", nullptr ), INSTRUCTION("0B", nullptr ), INSTRUCTION("0C", nullptr ), INSTRUCTION("0D", nullptr ), INSTRUCTION("0E", RRC_indexed_iy ), INSTRUCTION("0F", nullptr ),
    INSTRUCTION("10", nullptr ), INSTRUCTION("11", nullptr ), INSTRUCTION("12", nullptr ), INSTRUCTION("13", nullptr ), INSTRUCTION("14", nullptr ), INSTRUCTION("15", nullptr ), INSTRUCTION("16", RL_indexed_iy ), INSTRUCTION("17", nullptr ), INSTRUCTION("18", nullptr ), INSTRUCTION("19", nullptr ), INSTRUCTION("1A", nullptr ), INSTRUCTION("1B", nullptr ), INSTRUCTION("1C", nullptr ), INSTRUCTION("1D", nullptr ), INSTRUCTION("1E", RR_indexed_iy ), INSTRUCTION("1F", nullptr ),
    INSTRUCTION("20", nullptr ), INSTRUCTION("21", nullptr ), INSTRUCTION("22", nullptr ), INSTRUCTION("23", nullptr ), INSTRUCTION("24", nullptr ), INSTRUCTION("25", nullptr ), INSTRUCTION("26", SLA_indexed_iy ), INSTRUCTION("27", nullptr ), INSTRUCTION("28", nullptr ), INSTRUCTION("29", nullptr ), INSTRUCTION("2A", nullptr ), INSTRUCTION("2B", nullptr ), INSTRUCTION("2C", nullptr ), INSTRUCTION("2D", nullptr ), INSTRUCTION("2E", SRA_indexed_iy ), INSTRUCTION("2F", nullptr ),
    INSTRUCTION("30", nullptr ), INSTRUCTION("31", nullptr ), INSTRUCTION("32", nullptr ), INSTRUCTION("33", nullptr ), INSTRUCTION("34", nullptr ), INSTRUCTION("35", nullptr ), INSTRUCTION("36", nullptr ), INSTRUCTION("37", nullptr ), INSTRUCTION("38", nullptr ), INSTRUCTION("39", nullptr ), INSTRUCTION("3A", nullptr ), INSTRUCTION("3B", nullptr ), INSTRUCTION("3C", nullptr ), INSTRUCTION("3D", nullptr ), INSTRUCTION("3E", SRL_indexed_iy ), INSTRUCTION("3F", nullptr ),
    INSTRUCTION("40", nullptr ), INSTRUCTION("41", nullptr ), INSTRUCTION("42", nullptr ), INSTRUCTION("43", nullptr ), INSTRUCTION("44", nullptr ), INSTRUCTION("45", nullptr ), INSTRUCTION("46", BIT_indexed_iy ), INSTRUCTION("47", nullptr ), INSTRUCTION("48", nullptr ), INSTRUCTION("49", nullptr ), INSTRUCTION("4A", nullptr ), INSTRUCTION("4B", nullptr ), INSTRUCTION("4C", nullptr ), INSTRUCTION("4D", nullptr ), INSTRUCTION("4E", BIT_indexed_iy ), INSTRUCTION("4F", nullptr ),
    INSTRUCTION("50", nullptr ), INSTRUCTION("51", nullptr ), INSTRUCTION("52", nullptr ), INSTRUCTION("53", nullptr ), INSTRUCTION("54", nullptr ), INSTRUCTION("55", nullptr ), INSTRUCTION("56", BIT_indexed_iy ), INSTRUCTION("57", nullptr ), INSTRUCTION("58", nullptr ), INSTRUCTION("59", nullptr ), INSTRUCTION("5A", nullptr ), INSTRUCTION("5B", nullptr ), INSTRUCTION("5C", nullptr ), INSTRUCTION("5D", nullptr ), INSTRUCTION("5E", BIT_indexed_iy ), INSTRUCTION("5F", nullptr ),
    INSTRUCTION("60", nullptr ), INSTRUCTION("61", nullptr ), INSTRUCTION("62", nullptr ), INSTRUCTION("63", nullptr ), INSTRUCTION("64", nullptr ), INSTRUCTION("65", nullptr ), INSTRUCTION("66", BIT_indexed_iy ), INSTRUCTION("67", nullptr ), INSTRUCTION("68", nullptr ), INSTRUCTION("69", nullptr ), INSTRUCTION("6A", nullptr ), INSTRUCTION("6B", nullptr ), INSTRUCTION("6C", nullptr ), INSTRUCTION("6D", nullptr ), INSTRUCTION("6E", BIT_indexed_iy ), INSTRUCTION("6F", nullptr ),
    INSTRUCTION("70", nullptr ), INSTRUCTION("71", nullptr ), INSTRUCTION("72", nullptr ), INSTRUCTION("73", nullptr ), INSTRUCTION("74", nullptr ), INSTRUCTION("75", nullptr ), INSTRUCTION("76", BIT_indexed_iy ), INSTRUCTION("77", nullptr ), INSTRUCTION("78", nullptr ), INSTRUCTION("79", nullptr ), INSTRUCTION("7A", nullptr ), INSTRUCTION("7B", nullptr ), INSTRUCTION("7C", nullptr ), INSTRUCTION("7D", nullptr ), INSTRUCTION("7E", BIT_indexed_iy ), INSTRUCTION("7F", nullptr ),
    INSTRUCTION("80", nullptr ), INSTRUCTION("81", nullptr ), INSTRUCTION("82", nullptr ), INSTRUCTION("83", nullptr ), INSTRUCTION("84", nullptr ), INSTRUCTION("85", nullptr ), INSTRUCTION("86", RES_indexed_iy ), INSTRUCTION("87", nullptr ), INSTRUCTION("88", nullptr ), INSTRUCTION("89", nullptr ), INSTRUCTION("8A", nullptr ), INSTRUCTION("8B", nullptr ), INSTRUCTION("8C", nullptr ), INSTRUCTION("8D", nullptr ), INSTRUCTION("8E", RES_indexed_iy ), INSTRUCTION("8F", nullptr ),
    INSTRUCTION("90", nullptr ), INSTRUCTION("91", nullptr ), INSTRUCTION("92", nullptr ), INSTRUCTION("93", nullptr ), INSTRUCTION("94", nullptr ), INSTRUCTION("95", nullptr ), INSTRUCTION("96", RES_indexed_iy ), INSTRUCTION("97", nullptr ), INSTRUCTION("98", nullptr ), INSTRUCTION("99", nullptr ), INSTRUCTION("9A", nullptr ), INSTRUCTION("9B", nullptr ), INSTRUCTION("9C", nullptr ), INSTRUCTION("9D", nullptr ), INSTRUCTION("9E", RES_indexed_iy ), INSTRUCTION("9F", nullptr ),
    INSTRUCTION("A0", nullptr ), INSTRUCTION("A1", nullptr ), INSTRUCTION("A2", nullptr ), INSTRUCTION("A3", nullptr ), INSTRUCTION("A4", nullptr ), INSTRUCTION("A5", nullptr ), INSTRUCTION("A6", RES_indexed_iy ), INSTRUCTION("A7", nullptr ), INSTRUCTION("A8", nullptr ), INSTRUCTION("A9", nullptr ), INSTRUCTION("AA", nullptr ), INSTRUCTION("AB", nullptr ), INSTRUCTION("AC", nullptr ), INSTRUCTION("AD", nullptr ), INSTRUCTION("AE", RES_indexed_iy ), INSTRUCTION("AF", nullptr ),
    INSTRUCTION("B0", nullptr ), INSTRUCTION("B1", nullptr ), INSTRUCTION("B2", nullptr ), INSTRUCTION("B3", nullptr ), INSTRUCTION("B4", nullptr ), INSTRUCTION("B5", nullptr ), INSTRUCTION("B6", RES_indexed_iy ), INSTRUCTION("B7", nullptr ), INSTRUCTION("B8", nullptr ), INSTRUCTION("B9", nullptr ), INSTRUCTION("BA", nullptr ), INSTRUCTION("BB", nullptr ), INSTRUCTION("BC", nullptr ), INSTRUCTION("BD", nullptr ), INSTRUCTION("BE", RES_indexed_iy ), INSTRUCTION("BF", nullptr ),
    INSTRUCTION("C0", nullptr ), INSTRUCTION("C1", nullptr ), INSTRUCTION("C2", nullptr ), INSTRUCTION("C3", nullptr ), INSTRUCTION("C4", nullptr ), INSTRUCTION("C5", nullptr ), INSTRUCTION("C6", SET_indexed_iy ), INSTRUCTION("C7", nullptr ), INSTRUCTION("C8", nullptr ), INSTRUCTION("C9", nullptr ), INSTRUCTION("CA", nullptr ), INSTRUCTION("CB", nullptr ), INSTRUCTION("CC", nullptr ), INSTRUCTION("CD", nullptr ), INSTRUCTION("CE", SET_indexed_iy ), INSTRUCTION("CF", nullptr ),
    INSTRUCTION("D0", nullptr ), INSTRUCTION("D1", nullptr ), INSTRUCTION("D2", nullptr ), INSTRUCTION("D3", nullptr ), INSTRUCTION("D4", nullptr ), INSTRUCTION("D5", nullptr ), INSTRUCTION("D6", SET_indexed_iy ), INSTRUCTION("D7", nullptr ), INSTRUCTION("D8", nullptr ), INSTRUCTION("D9", nullptr ), INSTRUCTION("DA", nullptr ), INSTRUCTION("DB", nullptr ), INSTRUCTION("DC", nullptr ), INSTRUCTION("DD", nullptr ), INSTRUCTION("DE", SET_indexed_iy ), INSTRUCTION("DF", nullptr ),
    INSTRUCTION("E0", nullptr ), INSTRUCTION("E1", nullptr ), INSTRUCTION("E2", nullptr ), INSTRUCTION("E3", nullptr ), INSTRUCTION("E4", nullptr ), INSTRUCTION("E5", nullptr ), INSTRUCTION("E6", SET_indexed_iy ), INSTRUCTION("E7", nullptr ), INSTRUCTION("E8", nullptr ), INSTRUCTION("E9", nullptr ), INSTRUCTION("EA", nullptr ), INSTRUCTION("EB", nullptr ), INSTRUCTION("EC", nullptr ), INSTRUCTION("ED", nullptr ), INSTRUCTION("EE", SET_indexed_iy ), INSTRUCTION("EF", nullptr ),
    INSTRUCTION("F0", nullptr ), INSTRUCTION("F1", nullptr ), INSTRUCTION("F2", nullptr ), INSTRUCTION("F3", nullptr ), INSTRUCTION("F4", nullptr ), INSTRUCTION("F5", nullptr ), INSTRUCTION("F6", SET_indexed_iy ), INSTRUCTION("F7", nullptr ), INSTRUCTION("F8", nullptr ), INSTRUCTION("F9", nullptr ), INSTRUCTION("FA", nullptr ), INSTRUCTION("FB", nullptr ), INSTRUCTION("FC", nullptr ), INSTRUCTION("FD", nullptr ), INSTRUCTION("FE", SET_indexed_iy ), INSTRUCTION("FF", nullptr )
};

#endif